package handlers

import (
	"context"
	authpb "github.com/VolodymyrShabat/TestMicroservices/auth-service/pkg/proto"
)

// AuthHandler implements the gRPC server interface generated by protoc.
type AuthHandler struct {
	authpb.UnimplementedAuthServiceServer
}

func (h *AuthHandler) Login(ctx context.Context, req *authpb.LoginRequest) (*authpb.LoginResponse, error) {
	// Your business logic (e.g., verify credentia
	return &authpb.LoginResponse{Token: "yourToken is ready"}, nil
}

func (h *AuthHandler) ValidateToken(ctx context.Context, req *authpb.ValidateTokenRequest) (*authpb.ValidateTokenResponse, error) {
	// Your token validation logic

	return &authpb.ValidateTokenResponse{IsValid: true}, nil
}
