package handlers

import (
	"context"

	pb "github.com/VolodymyrShabat/testTask27NerdsAuthService/internal/proto" // import the generated code
)

// AuthHandler implements the gRPC server interface generated by protoc.
type AuthHandler struct {
	pb.UnimplementedAuthServiceServer
}

func (h *AuthHandler) Login(ctx context.Context, req *pb.LoginRequest) (*pb.LoginResponse, error) {
	// Your business logic (e.g., verify credentials)
	return &pb.LoginResponse{Token: "yourToken"}, nil
}

func (h *AuthHandler) ValidateToken(ctx context.Context, req *pb.ValidateTokenRequest) (*pb.ValidateTokenResponse, error) {
	// Your token validation logic
	return &pb.ValidateTokenResponse{IsValid: true}, nil
}
